# Generated by Django 3.1.1 on 2020-09-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='usage',
        ),
        migrations.AddField(
            model_name='records',
            name='avg_usage',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='records',
            name='max_usage',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='records',
            name='min_usage',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
