# Generated by Django 3.1.1 on 2020-09-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='secret_access_key',
            field=models.CharField(default='', max_length=500),
        ),
    ]
