# Generated by Django 3.1.1 on 2020-09-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_monitor', '0002_instance_secret_access_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='thresold',
            field=models.CharField(default='100', max_length=5),
        ),
    ]
