# Generated by Django 3.1.1 on 2020-09-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_monitor', '0003_instance_thresold'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='time',
            field=models.IntegerField(default=3600),
        ),
    ]
